name: Python test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: pip install . .[tests]

      - name: Run tests
        run: pytest
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: tests/ansible_vault_password

      - name: E2E test
        run: |
          python -m little_timmy -h 
          python -m little_timmy tests/repos/config_file_skip/repo -c tests/repos/config_file_skip/repo/.little-timmy 
          python -m little_timmy tests/repos/config_file_skip/repo
          python -m little_timmy tests/repos/alternate_layout/repo
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: tests/ansible_vault_password
